### ISSUE TITLE
我怎样获得一样有效的spiderId呢

### ISSUE THREAD

**Issue by Jiej009** [Northxw/Dianping#2]
想拉下代码试试
跑项目的时候 发现spiderId无效
{"ERRORCODE":"10063","RESULT":"请输入正确的spiderId!"}

**Comment by missmissfreya** [comment]
> 想拉下代码试试
> 跑项目的时候 发现spiderId无效
> {"ERRORCODE":"10063","RESULT":"请输入正确的spiderId!"}

请问你是如何解决的呢？

**Comment by Jiej009** [comment]
这个项目压根 放弃了。

**Comment by Jiej009** [comment]
> > 想拉下代码
> > 发现聪明跑项目的时候spiderId输入
> > {"ERRORCODE":"10063","RESULT":"请输入正确的spiderId!"}
> 
> 比如你是如何解决的呢？

这个项目压根 放弃了。
